services:
  api:
    build: .
    container_name: pelugestor_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    container_name: pelugestor_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: BotPeluTFG
      MYSQL_USER: reguue2
      MYSQL_PASSWORD: BotPeluTFG
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
